# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ross Jeffcoat
email: loopymonkey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        This is the personal site for Ross Jeffcoat.  
        #baseurl: "/dev/jekyll/_site" # the subpath of your site, e.g. /blog
baseurl: "" 
url: "http://www.rossjeffcoat.com" # the base hostname & protocol for your site
twitter_username: loopymonkey
github_username:  loopymonkey

# Build settings
markdown: kramdown

# plugins: [jekyll-youtube]
#  # This will require each of these gems automatically.